# -*- coding: utf-8 -*-
# Contenu cuisine — repris du menu hiver (PDF), traduit en 7 langues.
L = ["fr", "en", "it", "es", "de", "ru", "ar"]


def T(*v):
    return dict(zip(L, v))


def I(id, name, price, desc=None, img=None, tags=None, sub=None):
    d = {"id": id, "name": name, "price": price}
    if desc:
        d["desc"] = desc
    if img:
        d["img"] = img
    if tags:
        d["tags"] = tags
    if sub:
        d["sub"] = sub
    return d


FOOD = [
    {
        "id": "antipasti", "group": "cucina", "layout": "grid", "open": True,
        "title": "Antipasti",
        "kicker": T("À partager, ou pas", "To share, or not", "Da condividere, o no", "Para compartir, o no",
                    "Zum Teilen, oder auch nicht", "Чтобы делиться — или нет", "للمشاركة، أو لا"),
        "items": [
            I("salumi", "Piatto di Salumi", "18", T(
                "Sélection de charcuteries italiennes : jambon de Parme 24 mois, salami piquant, mortadelle à la pistache, speck et pain carasau croustillant.",
                "Selection of Italian cured meats: 24-month Parma ham, spicy salami, pistachio mortadella, speck and crispy carasau bread.",
                "Selezione di salumi italiani: prosciutto di Parma 24 mesi, salame piccante, mortadella al pistacchio, speck e pane carasau croccante.",
                "Selección de embutidos italianos: jamón de Parma 24 meses, salami picante, mortadela con pistacho, speck y pan carasau crujiente.",
                "Auswahl italienischer Wurstwaren: 24 Monate gereifter Parmaschinken, scharfe Salami, Pistazien-Mortadella, Speck und knuspriges Carasau-Brot.",
                "Ассорти итальянских мясных деликатесов: пармская ветчина 24 месяца, острая салями, мортаделла с фисташками, спек и хрустящий хлеб карасау.",
                "تشكيلة من اللحوم الإيطالية المقددة: لحم بارما معتّق 24 شهرًا، سلامي حار، مورتاديلا بالفستق، سبيك وخبز كاراساو مقرمش."), "salumi"),
            I("formaggi", "Piatto di Formaggi", "18", T(
                "Sélection de fromages italiens : parmesan Reggiano 18 mois, scamorza fumée, mozzarella di bufala, gorgonzola, marmelade de pomme maison et pain carasau croustillant.",
                "Selection of Italian cheeses: 18-month Parmigiano Reggiano, smoked scamorza, buffalo mozzarella, gorgonzola, homemade apple marmalade and crispy carasau bread.",
                "Selezione di formaggi italiani: Parmigiano Reggiano 18 mesi, scamorza affumicata, mozzarella di bufala, gorgonzola, marmellata di mele fatta in casa e pane carasau croccante.",
                "Selección de quesos italianos: Parmigiano Reggiano 18 meses, scamorza ahumada, mozzarella di bufala, gorgonzola, mermelada casera de manzana y pan carasau crujiente.",
                "Auswahl italienischer Käse: 18 Monate gereifter Parmigiano Reggiano, geräucherter Scamorza, Büffelmozzarella, Gorgonzola, hausgemachte Apfelmarmelade und knuspriges Carasau-Brot.",
                "Ассорти итальянских сыров: пармезан Реджано 18 месяцев, копчёная скаморца, моцарелла ди буфала, горгонзола, домашний яблочный мармелад и хрустящий хлеб карасау.",
                "تشكيلة من الأجبان الإيطالية: بارميزان ريجانو معتّق 18 شهرًا، سكامورزا مدخنة، موزاريلا الجاموس، غورغونزولا، مربى تفاح منزلي وخبز كاراساو مقرمش."), "formaggi", ["veggie"]),
            I("salumi-formaggi", "Piatto di Salumi e Formaggi", "22", T(
                "Sélection de charcuteries et fromages italiens servis avec notre focaccia et marmelade de pomme maison.",
                "Selection of Italian cured meats and cheeses served with our focaccia and homemade apple marmalade.",
                "Selezione di salumi e formaggi italiani serviti con la nostra focaccia e marmellata di mele fatta in casa.",
                "Selección de embutidos y quesos italianos servidos con nuestra focaccia y mermelada casera de manzana.",
                "Auswahl italienischer Wurst- und Käsesorten, serviert mit unserer Focaccia und hausgemachter Apfelmarmelade.",
                "Ассорти итальянских мясных деликатесов и сыров с нашей фокаччей и домашним яблочным мармеладом.",
                "تشكيلة من اللحوم المقددة والأجبان الإيطالية تُقدَّم مع الفوكاتشا ومربى التفاح المنزلي."), "salumi-formaggi"),
            I("arancino", "Arancino Cacio e Pepe", "15", T(
                "Boule de riz croustillante au pecorino romano et poivre noir, servie avec crème de parmesan, crème de truffe et tomates semi-confites.",
                "Crispy rice ball with pecorino romano and black pepper, served with Parmesan cream, truffle cream and semi-candied tomatoes.",
                "Palla di riso croccante al pecorino romano e pepe nero, servita con crema di parmigiano, crema al tartufo e pomodori semi-canditi.",
                "Bola de arroz crujiente con pecorino romano y pimienta negra, servida con crema de parmesano, crema de trufa y tomates semiconfitados.",
                "Knusprige Reiskugel mit Pecorino Romano und schwarzem Pfeffer, serviert mit Parmesancreme, Trüffelcreme und halbkandierten Tomaten.",
                "Хрустящий рисовый шарик с пекорино романо и чёрным перцем, с кремом из пармезана, трюфельным кремом и полуконфитюрными томатами.",
                "كرة أرز مقرمشة بجبن بيكورينو رومانو والفلفل الأسود، تُقدَّم مع كريمة البارميزان وكريمة الكمأة وطماطم نصف مسكّرة."), "arancino", ["veggie"]),
            I("caprese", "Caprese di Agata", "14", T(
                "Tomates fraîches de saison, mozzarella di bufala, pesto de basilic, amandes effilées, basilic frais et huile d'olive.",
                "Fresh seasonal tomatoes, buffalo mozzarella, basil pesto, flaked almonds, fresh basil and olive oil.",
                "Pomodori freschi di stagione, mozzarella di bufala, pesto di basilico, mandorle a lamelle, basilico fresco e olio d'oliva.",
                "Tomates frescos de temporada, mozzarella di bufala, pesto de albahaca, almendras laminadas, albahaca fresca y aceite de oliva.",
                "Frische Saisontomaten, Büffelmozzarella, Basilikumpesto, Mandelblättchen, frisches Basilikum und Olivenöl.",
                "Свежие сезонные томаты, моцарелла ди буфала, песто из базилика, миндальные лепестки, свежий базилик и оливковое масло.",
                "طماطم موسمية طازجة، موزاريلا الجاموس، بيستو الريحان، لوز مقطّع، ريحان طازج وزيت زيتون."), None, ["veggie"]),
            I("fritto", "Fritto Agata", "19", T(
                "Calamars frits dorés, servis avec une mayonnaise maison au basilic et citron.",
                "Golden fried calamari, served with homemade basil and lemon mayonnaise.",
                "Calamari fritti dorati, serviti con maionese fatta in casa al basilico e limone.",
                "Calamares fritos dorados, servidos con mayonesa casera de albahaca y limón.",
                "Goldbraun frittierte Calamari mit hausgemachter Basilikum-Zitronen-Mayonnaise.",
                "Золотистые жареные кальмары с домашним майонезом с базиликом и лимоном.",
                "حبار مقلي ذهبي يُقدَّم مع مايونيز منزلي بالريحان والليمون."), "fritto"),
            I("tataki", "Tataki di Tonno", "19", T(
                "Thon mi-cuit façon tataki, amandes effilées, sauce maison à la roquette, brunoise de poivrons poêlés et jeunes pousses de betterave.",
                "Seared tuna tataki, flaked almonds, homemade rocket sauce, diced pan-fried peppers and young beetroot shoots.",
                "Tonno scottato in stile tataki, mandorle a lamelle, salsa alla rucola fatta in casa, brunoise di peperoni saltati e germogli di barbabietola.",
                "Atún sellado estilo tataki, almendras laminadas, salsa casera de rúcula, brunoise de pimientos salteados y brotes de remolacha.",
                "Kurz angebratener Thunfisch nach Tataki-Art, Mandelblättchen, hausgemachte Rucolasauce, gebratene Paprikawürfel und junge Rote-Bete-Sprossen.",
                "Тунец татаки слабой прожарки, миндальные лепестки, домашний соус из рукколы, обжаренный сладкий перец брюнуаз и ростки свёклы.",
                "تونة تاتاكي نصف مطهية، لوز مقطّع، صلصة جرجير منزلية، فلفل محمّر مقطّع ناعمًا وبراعم الشمندر.")),
            I("carpaccio", "Carpaccio di Manzo", "19", T(
                "Fines tranches de bœuf mariné, fenouil croquant, copeaux de parmesan, pointe de réduction de pommes et huile d'olive bio.",
                "Thin slices of marinated beef, crunchy fennel, Parmesan shavings, a touch of apple reduction and organic olive oil.",
                "Sottili fette di manzo marinato, finocchio croccante, scaglie di parmigiano, un tocco di riduzione di mele e olio d'oliva bio.",
                "Finas láminas de ternera marinada, hinojo crujiente, virutas de parmesano, un toque de reducción de manzana y aceite de oliva ecológico.",
                "Dünne Scheiben mariniertes Rind, knackiger Fenchel, Parmesanspäne, ein Hauch Apfelreduktion und Bio-Olivenöl.",
                "Тонкие ломтики маринованной говядины, хрустящий фенхель, стружка пармезана, капля яблочной редукции и органическое оливковое масло.",
                "شرائح رقيقة من لحم البقر المتبّل، شمر مقرمش، رقائق البارميزان، لمسة من صلصة التفاح المركّزة وزيت زيتون عضوي."), "carpaccio"),
            I("vitello", "Vitello Tonnato", "19", T(
                "Fines tranches de noix de veau, sauce tonnata maison au thon, citron et anchois, artichauts grillés, fleur de câpres et tomates confites.",
                "Thin slices of veal, homemade tuna sauce with lemon and anchovies, grilled artichokes, caperberries and semi-candied tomatoes.",
                "Sottili fette di noce di vitello, salsa tonnata fatta in casa con tonno, limone e acciughe, carciofi grigliati, cucunci e pomodori confit.",
                "Finas láminas de ternera, salsa tonnata casera de atún, limón y anchoas, alcachofas a la parrilla, alcaparrones y tomates confitados.",
                "Dünne Kalbsscheiben, hausgemachte Thunfischsauce mit Zitrone und Sardellen, gegrillte Artischocken, Kapernäpfel und konfierte Tomaten.",
                "Тонкие ломтики телятины, домашний соус тоннато с тунцом, лимоном и анчоусами, артишоки гриль, каперсовые ягоды и томаты конфи.",
                "شرائح رقيقة من لحم العجل، صلصة تونّاتو منزلية بالتونة والليمون والأنشوجة، خرشوف مشوي، ثمار الكبر وطماطم مسكّرة."), "vitello"),
            I("tagliere", "Petite assiette de charcuterie", "7 – 9", T(
                "Au choix : jambon de Parme 24 mois 9 · bresaola 9 · salami piquant 7 · speck 7 · mortadelle à la pistache 7.",
                "Your choice: 24-month Parma ham 9 · bresaola 9 · spicy salami 7 · speck 7 · pistachio mortadella 7.",
                "A scelta: prosciutto di Parma 24 mesi 9 · bresaola 9 · salame piccante 7 · speck 7 · mortadella al pistacchio 7.",
                "A elegir: jamón de Parma 24 meses 9 · bresaola 9 · salami picante 7 · speck 7 · mortadela con pistacho 7.",
                "Nach Wahl: Parmaschinken 24 Monate 9 · Bresaola 9 · scharfe Salami 7 · Speck 7 · Pistazien-Mortadella 7.",
                "На выбор: пармская ветчина 24 месяца 9 · брезаола 9 · острая салями 7 · спек 7 · мортаделла с фисташками 7.",
                "حسب اختيارك: لحم بارما 24 شهرًا 9 · بريزاولا 9 · سلامي حار 7 · سبيك 7 · مورتاديلا بالفستق 7.")),
        ],
    },
    {
        "id": "burrata", "group": "cucina", "layout": "grid", "open": False,
        "title": "Creazioni Burrata",
        "kicker": T("Crémeuse, des Pouilles", "Creamy, from Puglia", "Cremosa, dalla Puglia", "Cremosa, de Apulia",
                    "Cremig, aus Apulien", "Нежная, из Апулии", "كريمية، من بوليا"),
        "items": [
            I("burrata-pomodorini", "Burrata & Pomodorini Arrosto", "13", T(
                "Burrata crémeuse des Pouilles, tomates cerises rôties, basilic frais et huile d'olive bio.",
                "Creamy burrata from Puglia, roasted cherry tomatoes, fresh basil and organic olive oil.",
                "Burrata cremosa pugliese, pomodorini arrosto, basilico fresco e olio d'oliva bio.",
                "Burrata cremosa de Apulia, tomates cherry asados, albahaca fresca y aceite de oliva ecológico.",
                "Cremige Burrata aus Apulien, geröstete Kirschtomaten, frisches Basilikum und Bio-Olivenöl.",
                "Нежная буррата из Апулии, запечённые томаты черри, свежий базилик и органическое оливковое масло.",
                "بوراتا كريمية من بوليا، طماطم كرزية محمّصة، ريحان طازج وزيت زيتون عضوي."), None, ["veggie"]),
            I("burrata-melone", "Burrata e Melone", "15", T(
                "Burrata crémeuse des Pouilles, marmelade de melon, jambon de Parme affiné 24 mois, basilic frais et huile d'olive bio.",
                "Creamy burrata from Puglia, melon marmalade, 24-month Parma ham, fresh basil and organic olive oil.",
                "Burrata cremosa pugliese, marmellata di melone, prosciutto di Parma stagionato 24 mesi, basilico fresco e olio d'oliva bio.",
                "Burrata cremosa de Apulia, mermelada de melón, jamón de Parma curado 24 meses, albahaca fresca y aceite de oliva ecológico.",
                "Cremige Burrata aus Apulien, Melonenmarmelade, 24 Monate gereifter Parmaschinken, frisches Basilikum und Bio-Olivenöl.",
                "Нежная буррата из Апулии, дынный мармелад, пармская ветчина 24 месяца, свежий базилик и органическое оливковое масло.",
                "بوراتا كريمية من بوليا، مربى البطيخ الأصفر، لحم بارما معتّق 24 شهرًا، ريحان طازج وزيت زيتون عضوي.")),
            I("burrata-tartufo", "Burrata e Tartufo", "18", T(
                "Burrata crémeuse des Pouilles, crème de truffe noire, copeaux de truffe fraîche, basilic frais et huile d'olive bio.",
                "Creamy burrata from Puglia, black truffle cream, fresh truffle shavings, fresh basil and organic olive oil.",
                "Burrata cremosa pugliese, crema di tartufo nero, scaglie di tartufo fresco, basilico fresco e olio d'oliva bio.",
                "Burrata cremosa de Apulia, crema de trufa negra, láminas de trufa fresca, albahaca fresca y aceite de oliva ecológico.",
                "Cremige Burrata aus Apulien, schwarze Trüffelcreme, frisch gehobelter Trüffel, frisches Basilikum und Bio-Olivenöl.",
                "Нежная буррата из Апулии, крем из чёрного трюфеля, стружка свежего трюфеля, свежий базилик и органическое оливковое масло.",
                "بوراتا كريمية من بوليا، كريمة الكمأة السوداء، رقائق كمأة طازجة، ريحان طازج وزيت زيتون عضوي."), "burrata-tartufo", ["veggie"]),
            I("focaccia", "Focaccia Maison", "4", T(
                "Huile d'olive bio, origan.", "Organic olive oil, oregano.", "Olio d'oliva bio, origano.",
                "Aceite de oliva ecológico, orégano.", "Bio-Olivenöl, Oregano.", "Органическое оливковое масло, орегано.",
                "زيت زيتون عضوي، أوريغانو."), None, ["vegan"]),
        ],
    },
    {
        "id": "piatti-caldi", "group": "cucina", "layout": "grid", "open": False,
        "title": "Piatti Caldi",
        "kicker": T("Nouveauté, tout droit du four", "New, straight from the oven", "Novità, dritti dal forno",
                    "Novedad, recién salidos del horno", "Neu, direkt aus dem Ofen", "Новинка, прямо из печи", "جديد، مباشرة من الفرن"),
        "items": [
            I("parmigiana", "Parmigiana di Agata", "16", T(
                "Aubergines dorées et fondantes, sauce tomate, mozzarella fior di latte, parmesan gratinés au four et basilic.",
                "Golden, melting aubergines, tomato sauce, fior di latte mozzarella and Parmesan, oven-gratinated, with basil.",
                "Melanzane dorate e fondenti, salsa di pomodoro, mozzarella fior di latte e parmigiano gratinati al forno, basilico.",
                "Berenjenas doradas y melosas, salsa de tomate, mozzarella fior di latte y parmesano gratinados al horno, albahaca.",
                "Goldene, zartschmelzende Auberginen, Tomatensauce, Fior-di-Latte-Mozzarella und Parmesan, im Ofen überbacken, mit Basilikum.",
                "Золотистые нежные баклажаны, томатный соус, моцарелла фьор ди латте и пармезан, запечённые в печи, с базиликом.",
                "باذنجان ذهبي طري، صلصة طماطم، موزاريلا فيور دي لاتيه وبارميزان مُحمّرة في الفرن، مع الريحان."), "parmigiana", ["veggie", "new"]),
            I("lasagne", "Lasagne al Forno", "20", T(
                "Pâtes fraîches superposées, sauce bolognaise mijotée, béchamel onctueuse, fior di latte et parmesan gratiné au four.",
                "Layers of fresh pasta, slow-cooked bolognese sauce, creamy béchamel, fior di latte and Parmesan, oven-gratinated.",
                "Strati di pasta fresca, ragù alla bolognese cotto a lungo, besciamella vellutata, fior di latte e parmigiano gratinati al forno.",
                "Capas de pasta fresca, salsa boloñesa a fuego lento, bechamel cremosa, fior di latte y parmesano gratinados al horno.",
                "Schichten frischer Pasta, langsam geschmorte Bolognese, cremige Béchamel, Fior di Latte und Parmesan, im Ofen überbacken.",
                "Слои свежей пасты, томлёный соус болоньезе, нежный бешамель, фьор ди латте и пармезан, запечённые в печи.",
                "طبقات من المعكرونة الطازجة، صلصة بولونيز مطهوة ببطء، بشاميل كريمي، فيور دي لاتيه وبارميزان مُحمّرة في الفرن."), "lasagne", ["new"]),
        ],
    },
    {
        "id": "insalate", "group": "cucina", "layout": "grid", "open": False,
        "title": "Insalate",
        "kicker": T("Fraîches et généreuses", "Fresh and generous", "Fresche e generose", "Frescas y generosas",
                    "Frisch und großzügig", "Свежие и щедрые", "طازجة وسخية"),
        "items": [
            I("cesare", "Cesare is Back !", "20", T(
                "Salade romaine croquante et trévise, suprême de poulet grillé, parmesan, tomates confites, basilic frais et croûtons dorés, relevés d'une sauce César maison.",
                "Crunchy romaine lettuce and radicchio, grilled chicken breast, Parmesan, semi-candied tomatoes, fresh basil and golden croutons, with homemade Caesar dressing.",
                "Lattuga romana croccante e radicchio, petto di pollo grigliato, parmigiano, pomodori confit, basilico fresco e crostini dorati, con salsa Caesar fatta in casa.",
                "Lechuga romana crujiente y radicchio, pechuga de pollo a la parrilla, parmesano, tomates confitados, albahaca fresca y picatostes dorados, con salsa César casera.",
                "Knackiger Romanasalat und Radicchio, gegrillte Hähnchenbrust, Parmesan, konfierte Tomaten, frisches Basilikum und goldene Croûtons mit hausgemachtem Caesar-Dressing.",
                "Хрустящий салат ромэн и радиккьо, куриная грудка гриль, пармезан, томаты конфи, свежий базилик и золотистые крутоны с домашним соусом «Цезарь».",
                "خس روماني مقرمش وراديكيو، صدر دجاج مشوي، بارميزان، طماطم مسكّرة، ريحان طازج وخبز محمّص ذهبي، مع صلصة سيزر منزلية."), "cesare"),
            I("polpo", "Polpo Fresco", "19", T(
                "Salade de poulpe, pommes de terre fondantes, fenouil croquant, mélange de salades, citron et huile d'olive bio.",
                "Octopus salad, tender potatoes, crunchy fennel, mixed leaves, lemon and organic olive oil.",
                "Insalata di polpo, patate fondenti, finocchio croccante, misticanza, limone e olio d'oliva bio.",
                "Ensalada de pulpo, patatas melosas, hinojo crujiente, mezcla de lechugas, limón y aceite de oliva ecológico.",
                "Oktopussalat, zarte Kartoffeln, knackiger Fenchel, gemischte Blattsalate, Zitrone und Bio-Olivenöl.",
                "Салат из осьминога, нежный картофель, хрустящий фенхель, микс салатов, лимон и органическое оливковое масло.",
                "سلطة أخطبوط، بطاطس طرية، شمر مقرمش، تشكيلة خضار ورقية، ليمون وزيت زيتون عضوي.")),
            I("pugliese", "La Pugliese", "18", T(
                "Stracciatella crémeuse, tomates fraîches, oignons rouges, jambon de Parme affiné 24 mois, sucrine et roquette, éclats de noisettes du Piémont, vinaigrette maison et basilic.",
                "Creamy stracciatella, fresh tomatoes, red onions, 24-month Parma ham, little gem and rocket, Piedmont hazelnuts, homemade vinaigrette and basil.",
                "Stracciatella cremosa, pomodori freschi, cipolle rosse, prosciutto di Parma stagionato 24 mesi, lattughino e rucola, granella di nocciole piemontesi, vinaigrette della casa e basilico.",
                "Stracciatella cremosa, tomates frescos, cebolla morada, jamón de Parma curado 24 meses, cogollos y rúcula, avellanas del Piamonte, vinagreta casera y albahaca.",
                "Cremige Stracciatella, frische Tomaten, rote Zwiebeln, 24 Monate gereifter Parmaschinken, Romanaherzen und Rucola, Piemonteser Haselnüsse, hausgemachte Vinaigrette und Basilikum.",
                "Нежная страчателла, свежие томаты, красный лук, пармская ветчина 24 месяца, латук и руккола, пьемонтский фундук, домашняя заправка и базилик.",
                "ستراتشاتيلا كريمية، طماطم طازجة، بصل أحمر، لحم بارما معتّق 24 شهرًا، خس صغير وجرجير، بندق من بيدمونت، صلصة منزلية وريحان."), "pugliese"),
            I("mista", "Insalata Mista", "14", T(
                "Mélange frais de sucrine, roquette, courgettes, carottes et tomates, parsemé de granella de pistaches croquantes, vinaigrette maison et basilic.",
                "Fresh mix of little gem, rocket, courgettes, carrots and tomatoes, sprinkled with crunchy pistachio granella, homemade vinaigrette and basil.",
                "Mix fresco di lattughino, rucola, zucchine, carote e pomodori, con granella di pistacchi croccante, vinaigrette della casa e basilico.",
                "Mezcla fresca de cogollos, rúcula, calabacín, zanahoria y tomate, con pistachos crujientes troceados, vinagreta casera y albahaca.",
                "Frische Mischung aus Romanaherzen, Rucola, Zucchini, Karotten und Tomaten mit knusprigen Pistazienstückchen, hausgemachter Vinaigrette und Basilikum.",
                "Свежий микс латука, рукколы, цукини, моркови и томатов с хрустящей фисташковой крошкой, домашней заправкой и базиликом.",
                "مزيج طازج من الخس الصغير والجرجير والكوسا والجزر والطماطم، مع فستق مجروش مقرمش وصلصة منزلية وريحان."), "mista", ["vegan"]),
        ],
    },
    {
        "id": "pizze-classiche", "group": "cucina", "layout": "wide", "open": False,
        "title": "Pizze Classiche",
        "kicker": T("Pâte napolitaine, cuite au feu de bois", "Neapolitan dough, wood-fired", "Impasto napoletano, cotto a legna",
                    "Masa napolitana, al horno de leña", "Neapolitanischer Teig, aus dem Holzofen", "Неаполитанское тесто, дровяная печь", "عجينة نابولية، مخبوزة على الحطب"),
        "items": [
            I("margherita", "Margherita", "14", T(
                "Sauce tomate San Marzano D.O.P., mozzarella fior di latte, huile d'olive, basilic frais.",
                "San Marzano D.O.P. tomato sauce, fior di latte mozzarella, olive oil, fresh basil.",
                "Salsa di pomodoro San Marzano D.O.P., mozzarella fior di latte, olio d'oliva, basilico fresco.",
                "Salsa de tomate San Marzano D.O.P., mozzarella fior di latte, aceite de oliva, albahaca fresca.",
                "Tomatensauce aus San-Marzano-Tomaten (D.O.P.), Fior-di-Latte-Mozzarella, Olivenöl, frisches Basilikum.",
                "Томатный соус Сан-Марцано D.O.P., моцарелла фьор ди латте, оливковое масло, свежий базилик.",
                "صلصة طماطم سان مارزانو D.O.P.، موزاريلا فيور دي لاتيه، زيت زيتون، ريحان طازج."), "margherita", ["veggie"]),
            I("marinara", "Marinara Speciale", "13", T(
                "Sauce tomate San Marzano D.O.P., anchois, olives noires, ail, origan, huile d'olive et basilic frais.",
                "San Marzano D.O.P. tomato sauce, anchovies, black olives, garlic, oregano, olive oil and fresh basil.",
                "Salsa di pomodoro San Marzano D.O.P., acciughe, olive nere, aglio, origano, olio d'oliva e basilico fresco.",
                "Salsa de tomate San Marzano D.O.P., anchoas, aceitunas negras, ajo, orégano, aceite de oliva y albahaca fresca.",
                "San-Marzano-Tomatensauce (D.O.P.), Sardellen, schwarze Oliven, Knoblauch, Oregano, Olivenöl und frisches Basilikum.",
                "Томатный соус Сан-Марцано D.O.P., анчоусы, чёрные оливки, чеснок, орегано, оливковое масло и свежий базилик.",
                "صلصة طماطم سان مارزانو D.O.P.، أنشوجة، زيتون أسود، ثوم، أوريغانو، زيت زيتون وريحان طازج."), "marinara"),
            I("queen", "Queen des Près", "18", T(
                "Sauce tomate San Marzano D.O.P., mozzarella fior di latte, jambon cuit, champignons, huile d'olive et basilic frais.",
                "San Marzano D.O.P. tomato sauce, fior di latte mozzarella, cooked ham, mushrooms, olive oil and fresh basil.",
                "Salsa di pomodoro San Marzano D.O.P., mozzarella fior di latte, prosciutto cotto, funghi, olio d'oliva e basilico fresco.",
                "Salsa de tomate San Marzano D.O.P., mozzarella fior di latte, jamón cocido, champiñones, aceite de oliva y albahaca fresca.",
                "San-Marzano-Tomatensauce (D.O.P.), Fior-di-Latte-Mozzarella, Kochschinken, Champignons, Olivenöl und frisches Basilikum.",
                "Томатный соус Сан-Марцано D.O.P., моцарелла фьор ди латте, варёная ветчина, шампиньоны, оливковое масло и свежий базилик.",
                "صلصة طماطم سان مارزانو D.O.P.، موزاريلا فيور دي لاتيه، لحم مطبوخ، فطر، زيت زيتون وريحان طازج."), "queen"),
            I("diavola", "Diavola", "17", T(
                "Sauce tomate San Marzano D.O.P., mozzarella fior di latte, salami piquant (spianata), huile d'olive et basilic frais.",
                "San Marzano D.O.P. tomato sauce, fior di latte mozzarella, spicy salami (spianata), olive oil and fresh basil.",
                "Salsa di pomodoro San Marzano D.O.P., mozzarella fior di latte, salame piccante (spianata), olio d'oliva e basilico fresco.",
                "Salsa de tomate San Marzano D.O.P., mozzarella fior di latte, salami picante (spianata), aceite de oliva y albahaca fresca.",
                "San-Marzano-Tomatensauce (D.O.P.), Fior-di-Latte-Mozzarella, scharfe Salami (Spianata), Olivenöl und frisches Basilikum.",
                "Томатный соус Сан-Марцано D.O.P., моцарелла фьор ди латте, острая салями (спьяната), оливковое масло и свежий базилик.",
                "صلصة طماطم سان مارزانو D.O.P.، موزاريلا فيور دي لاتيه، سلامي حار (سبياناتا)، زيت زيتون وريحان طازج."), "diavola", ["spicy"]),
            I("capricieuse", "La Capricieuse", "19", T(
                "Sauce tomate San Marzano D.O.P., mozzarella fior di latte, artichauts grillés, champignons, jambon cuit, salami napolitain, olives noires, huile d'olive et basilic frais.",
                "San Marzano D.O.P. tomato sauce, fior di latte mozzarella, grilled artichokes, mushrooms, cooked ham, Neapolitan salami, black olives, olive oil and fresh basil.",
                "Salsa di pomodoro San Marzano D.O.P., mozzarella fior di latte, carciofi grigliati, funghi, prosciutto cotto, salame napoletano, olive nere, olio d'oliva e basilico fresco.",
                "Salsa de tomate San Marzano D.O.P., mozzarella fior di latte, alcachofas a la parrilla, champiñones, jamón cocido, salami napolitano, aceitunas negras, aceite de oliva y albahaca fresca.",
                "San-Marzano-Tomatensauce (D.O.P.), Fior-di-Latte-Mozzarella, gegrillte Artischocken, Champignons, Kochschinken, neapolitanische Salami, schwarze Oliven, Olivenöl und frisches Basilikum.",
                "Томатный соус Сан-Марцано D.O.P., моцарелла фьор ди латте, артишоки гриль, шампиньоны, варёная ветчина, неаполитанская салями, чёрные оливки, оливковое масло и свежий базилик.",
                "صلصة طماطم سان مارزانو D.O.P.، موزاريلا فيور دي لاتيه، خرشوف مشوي، فطر، لحم مطبوخ، سلامي نابولي، زيتون أسود، زيت زيتون وريحان طازج."), "capricieuse"),
            I("healthy", "Healthy Mood", "17", T(
                "Sauce tomate jaune, poivrons poêlés, champignons, olives noires, artichauts grillés, amandes effilées, basilic frais et huile d'olive. Supplément fior di latte +4.",
                "Yellow tomato sauce, pan-fried peppers, mushrooms, black olives, grilled artichokes, flaked almonds, fresh basil and olive oil. Extra fior di latte +4.",
                "Salsa di pomodoro giallo, peperoni saltati, funghi, olive nere, carciofi grigliati, mandorle a lamelle, basilico fresco e olio d'oliva. Supplemento fior di latte +4.",
                "Salsa de tomate amarillo, pimientos salteados, champiñones, aceitunas negras, alcachofas a la parrilla, almendras laminadas, albahaca fresca y aceite de oliva. Suplemento fior di latte +4.",
                "Gelbe Tomatensauce, gebratene Paprika, Champignons, schwarze Oliven, gegrillte Artischocken, Mandelblättchen, frisches Basilikum und Olivenöl. Extra Fior di Latte +4.",
                "Соус из жёлтых томатов, обжаренный перец, шампиньоны, чёрные оливки, артишоки гриль, миндальные лепестки, свежий базилик и оливковое масло. Добавить фьор ди латте +4.",
                "صلصة طماطم صفراء، فلفل محمّر، فطر، زيتون أسود، خرشوف مشوي، لوز مقطّع، ريحان طازج وزيت زيتون. إضافة فيور دي لاتيه +4."), "healthy", ["vegan"]),
            I("calzone", "Calzone", "20", T(
                "Sauce tomate San Marzano D.O.P., mozzarella fior di latte, jambon cuit, salami napolitain, ricotta, poivre noir, basilic frais et huile d'olive. Forme et préparation authentiques, comme à Naples !",
                "San Marzano D.O.P. tomato sauce, fior di latte mozzarella, cooked ham, Neapolitan salami, ricotta, black pepper, fresh basil and olive oil. Authentic shape and preparation, just like in Naples!",
                "Salsa di pomodoro San Marzano D.O.P., mozzarella fior di latte, prosciutto cotto, salame napoletano, ricotta, pepe nero, basilico fresco e olio d'oliva. Forma e preparazione autentiche, come a Napoli!",
                "Salsa de tomate San Marzano D.O.P., mozzarella fior di latte, jamón cocido, salami napolitano, ricotta, pimienta negra, albahaca fresca y aceite de oliva. ¡Forma y elaboración auténticas, como en Nápoles!",
                "San-Marzano-Tomatensauce (D.O.P.), Fior-di-Latte-Mozzarella, Kochschinken, neapolitanische Salami, Ricotta, schwarzer Pfeffer, frisches Basilikum und Olivenöl. Echte Form und Zubereitung, wie in Neapel!",
                "Томатный соус Сан-Марцано D.O.P., моцарелла фьор ди латте, варёная ветчина, неаполитанская салями, рикотта, чёрный перец, свежий базилик и оливковое масло. Настоящая форма и рецепт — как в Неаполе!",
                "صلصة طماطم سان مارزانو D.O.P.، موزاريلا فيور دي لاتيه، لحم مطبوخ، سلامي نابولي، ريكوتا، فلفل أسود، ريحان طازج وزيت زيتون. الشكل والتحضير الأصليان، تمامًا كما في نابولي!"), "calzone"),
            I("bambino", "Pizza Bambino", "10", T(
                "Jusqu'à 12 ans. Sauce tomate San Marzano D.O.P., fior di latte, jambon cuit, huile d'olive bio, basilic.",
                "Up to 12 years old. San Marzano D.O.P. tomato sauce, fior di latte, cooked ham, organic olive oil, basil.",
                "Fino a 12 anni. Salsa di pomodoro San Marzano D.O.P., fior di latte, prosciutto cotto, olio d'oliva bio, basilico.",
                "Hasta 12 años. Salsa de tomate San Marzano D.O.P., fior di latte, jamón cocido, aceite de oliva ecológico, albahaca.",
                "Bis 12 Jahre. San-Marzano-Tomatensauce (D.O.P.), Fior di Latte, Kochschinken, Bio-Olivenöl, Basilikum.",
                "Для детей до 12 лет. Томатный соус Сан-Марцано D.O.P., фьор ди латте, варёная ветчина, органическое оливковое масло, базилик.",
                "حتى 12 عامًا. صلصة طماطم سان مارزانو D.O.P.، فيور دي لاتيه، لحم مطبوخ، زيت زيتون عضوي، ريحان.")),
        ],
    },
    {
        "id": "pizze-signature", "group": "cucina", "layout": "wide", "open": False,
        "title": "Pizze Signature",
        "kicker": T("Créations Agata", "Agata creations", "Creazioni Agata", "Creaciones Agata", "Agata-Kreationen",
                    "Авторские пиццы Agata", "إبداعات أغاتا"),
        "items": [
            I("via-chiaia", "Via Chiaia", "22", T(
                "Focaccia garnie de tomates cerises, mozzarella di bufala, jambon de Parme affiné 24 mois, roquette, copeaux de parmesan, basilic frais et huile d'olive.",
                "Focaccia topped with cherry tomatoes, buffalo mozzarella, 24-month Parma ham, rocket, Parmesan shavings, fresh basil and olive oil.",
                "Focaccia con pomodorini, mozzarella di bufala, prosciutto di Parma stagionato 24 mesi, rucola, scaglie di parmigiano, basilico fresco e olio d'oliva.",
                "Focaccia con tomates cherry, mozzarella di bufala, jamón de Parma curado 24 meses, rúcula, virutas de parmesano, albahaca fresca y aceite de oliva.",
                "Focaccia mit Kirschtomaten, Büffelmozzarella, 24 Monate gereiftem Parmaschinken, Rucola, Parmesanspänen, frischem Basilikum und Olivenöl.",
                "Фокачча с томатами черри, моцареллой ди буфала, пармской ветчиной 24 месяца, рукколой, стружкой пармезана, свежим базиликом и оливковым маслом.",
                "فوكاتشا بالطماطم الكرزية وموزاريلا الجاموس ولحم بارما المعتّق 24 شهرًا والجرجير ورقائق البارميزان والريحان الطازج وزيت الزيتون."), "via-chiaia"),
            I("cheese-addict", "Cheese Addict", "19", T(
                "Mozzarella fior di latte, ricotta, gorgonzola, scamorza fumée et cialda de parmigiano, huile d'olive et basilic frais.",
                "Fior di latte mozzarella, ricotta, gorgonzola, smoked scamorza and Parmesan crisp, olive oil and fresh basil.",
                "Mozzarella fior di latte, ricotta, gorgonzola, scamorza affumicata e cialda di parmigiano, olio d'oliva e basilico fresco.",
                "Mozzarella fior di latte, ricotta, gorgonzola, scamorza ahumada y teja de parmesano, aceite de oliva y albahaca fresca.",
                "Fior-di-Latte-Mozzarella, Ricotta, Gorgonzola, geräucherter Scamorza und Parmesan-Chip, Olivenöl und frisches Basilikum.",
                "Моцарелла фьор ди латте, рикотта, горгонзола, копчёная скаморца и чипс из пармезана, оливковое масло и свежий базилик.",
                "موزاريلا فيور دي لاتيه، ريكوتا، غورغونزولا، سكامورزا مدخنة ورقاقة بارميزان، زيت زيتون وريحان طازج."), "cheese-addict", ["veggie"]),
            I("agatissima", "Agatissima", "18", T(
                "Crème de tomate jaune, burrata crémeuse des Pouilles, roquette, basilic frais et huile d'olive.",
                "Yellow tomato cream, creamy burrata from Puglia, rocket, fresh basil and olive oil.",
                "Crema di pomodoro giallo, burrata cremosa pugliese, rucola, basilico fresco e olio d'oliva.",
                "Crema de tomate amarillo, burrata cremosa de Apulia, rúcula, albahaca fresca y aceite de oliva.",
                "Gelbe Tomatencreme, cremige Burrata aus Apulien, Rucola, frisches Basilikum und Olivenöl.",
                "Крем из жёлтых томатов, нежная буррата из Апулии, руккола, свежий базилик и оливковое масло.",
                "كريمة الطماطم الصفراء، بوراتا كريمية من بوليا، جرجير، ريحان طازج وزيت زيتون."), "agatissima", ["veggie"]),
            I("perla-nera", "Perla Nera is back !", "26", T(
                "Mozzarella fior di latte, crème de parmesan et crème de truffe 10 %, relevées d'un tour de poivre, basilic frais et truffe fraîche.",
                "Fior di latte mozzarella, Parmesan cream and 10% truffle cream, a twist of pepper, fresh basil and fresh truffle.",
                "Mozzarella fior di latte, crema di parmigiano e crema al tartufo 10%, un giro di pepe, basilico fresco e tartufo fresco.",
                "Mozzarella fior di latte, crema de parmesano y crema de trufa al 10 %, un toque de pimienta, albahaca fresca y trufa fresca.",
                "Fior-di-Latte-Mozzarella, Parmesancreme und 10 % Trüffelcreme, ein Hauch Pfeffer, frisches Basilikum und frischer Trüffel.",
                "Моцарелла фьор ди латте, крем из пармезана и трюфельный крем 10 %, щепотка перца, свежий базилик и свежий трюфель.",
                "موزاريلا فيور دي لاتيه، كريمة البارميزان وكريمة الكمأة 10%، رشة فلفل، ريحان طازج وكمأة طازجة."), "perla-nera", ["veggie"]),
            I("bellezza", "Bellezza", "23", T(
                "Fior di latte, crème de tomate jaune, stracciatella di bufala, figues fraîches, jambon de Parme 24 mois, noisettes du Piémont, confiture de figues, basilic frais et huile d'olive.",
                "Fior di latte, yellow tomato cream, buffalo stracciatella, fresh figs, 24-month Parma ham, Piedmont hazelnuts, fig jam, fresh basil and olive oil.",
                "Fior di latte, crema di pomodoro giallo, stracciatella di bufala, fichi freschi, prosciutto di Parma 24 mesi, nocciole piemontesi, confettura di fichi, basilico fresco e olio d'oliva.",
                "Fior di latte, crema de tomate amarillo, stracciatella di bufala, higos frescos, jamón de Parma 24 meses, avellanas del Piamonte, confitura de higos, albahaca fresca y aceite de oliva.",
                "Fior di Latte, gelbe Tomatencreme, Büffel-Stracciatella, frische Feigen, 24 Monate gereifter Parmaschinken, Piemonteser Haselnüsse, Feigenkonfitüre, frisches Basilikum und Olivenöl.",
                "Фьор ди латте, крем из жёлтых томатов, страчателла ди буфала, свежий инжир, пармская ветчина 24 месяца, пьемонтский фундук, инжирный джем, свежий базилик и оливковое масло.",
                "فيور دي لاتيه، كريمة الطماطم الصفراء، ستراتشاتيلا الجاموس، تين طازج، لحم بارما 24 شهرًا، بندق بيدمونت، مربى التين، ريحان طازج وزيت زيتون.")),
            I("pistacchiosa", "Pistacchiosa", "22", T(
                "Focaccia garnie de mortadelle, stracciatella di bufala, granella de pistaches, pesto de pistaches maison et basilic frais.",
                "Focaccia topped with mortadella, buffalo stracciatella, crushed pistachios, homemade pistachio pesto and fresh basil.",
                "Focaccia con mortadella, stracciatella di bufala, granella di pistacchi, pesto di pistacchi fatto in casa e basilico fresco.",
                "Focaccia con mortadela, stracciatella di bufala, pistachos troceados, pesto casero de pistacho y albahaca fresca.",
                "Focaccia mit Mortadella, Büffel-Stracciatella, Pistazienstückchen, hausgemachtem Pistazienpesto und frischem Basilikum.",
                "Фокачча с мортаделлой, страчателлой ди буфала, фисташковой крошкой, домашним фисташковым песто и свежим базиликом.",
                "فوكاتشا بالمورتاديلا وستراتشاتيلا الجاموس والفستق المجروش وبيستو الفستق المنزلي والريحان الطازج.")),
            I("alla-norma", "Alla Norma", "23", T(
                "Sauce tomate San Marzano D.O.P., mozzarella fior di latte, aubergines frites, ricotta salata, carpaccio de bresaola, basilic frais et huile d'olive.",
                "San Marzano D.O.P. tomato sauce, fior di latte mozzarella, fried aubergines, ricotta salata, bresaola carpaccio, fresh basil and olive oil.",
                "Salsa di pomodoro San Marzano D.O.P., mozzarella fior di latte, melanzane fritte, ricotta salata, carpaccio di bresaola, basilico fresco e olio d'oliva.",
                "Salsa de tomate San Marzano D.O.P., mozzarella fior di latte, berenjenas fritas, ricotta salata, carpaccio de bresaola, albahaca fresca y aceite de oliva.",
                "San-Marzano-Tomatensauce (D.O.P.), Fior-di-Latte-Mozzarella, frittierte Auberginen, Ricotta salata, Bresaola-Carpaccio, frisches Basilikum und Olivenöl.",
                "Томатный соус Сан-Марцано D.O.P., моцарелла фьор ди латте, жареные баклажаны, солёная рикотта, карпаччо из брезаолы, свежий базилик и оливковое масло.",
                "صلصة طماطم سان مارزانو D.O.P.، موزاريلا فيور دي لاتيه، باذنجان مقلي، ريكوتا مملحة، كارباتشيو بريزاولا، ريحان طازج وزيت زيتون.")),
            I("siciliana", "Siciliana", "23", T(
                "Mozzarella fior di latte, crème de tomate jaune, stracciatella di bufala, bresaola, granella de pistaches, pesto de pistaches maison et basilic frais.",
                "Fior di latte mozzarella, yellow tomato cream, buffalo stracciatella, bresaola, crushed pistachios, homemade pistachio pesto and fresh basil.",
                "Mozzarella fior di latte, crema di pomodoro giallo, stracciatella di bufala, bresaola, granella di pistacchi, pesto di pistacchi fatto in casa e basilico fresco.",
                "Mozzarella fior di latte, crema de tomate amarillo, stracciatella di bufala, bresaola, pistachos troceados, pesto casero de pistacho y albahaca fresca.",
                "Fior-di-Latte-Mozzarella, gelbe Tomatencreme, Büffel-Stracciatella, Bresaola, Pistazienstückchen, hausgemachtes Pistazienpesto und frisches Basilikum.",
                "Моцарелла фьор ди латте, крем из жёлтых томатов, страчателла ди буфала, брезаола, фисташковая крошка, домашний фисташковый песто и свежий базилик.",
                "موزاريلا فيور دي لاتيه، كريمة الطماطم الصفراء، ستراتشاتيلا الجاموس، بريزاولا، فستق مجروش، بيستو الفستق المنزلي وريحان طازج.")),
            I("san-valentina", "San Valentina", "23", T(
                "Mozzarella fior di latte, pesto de basilic, stracciatella di bufala, speck, tuile de parmesan, tomates confites, basilic frais et huile d'olive.",
                "Fior di latte mozzarella, basil pesto, buffalo stracciatella, speck, Parmesan tuile, semi-candied tomatoes, fresh basil and olive oil.",
                "Mozzarella fior di latte, pesto di basilico, stracciatella di bufala, speck, cialda di parmigiano, pomodori confit, basilico fresco e olio d'oliva.",
                "Mozzarella fior di latte, pesto de albahaca, stracciatella di bufala, speck, teja de parmesano, tomates confitados, albahaca fresca y aceite de oliva.",
                "Fior-di-Latte-Mozzarella, Basilikumpesto, Büffel-Stracciatella, Speck, Parmesanhippe, konfierte Tomaten, frisches Basilikum und Olivenöl.",
                "Моцарелла фьор ди латте, песто из базилика, страчателла ди буфала, спек, тюиль из пармезана, томаты конфи, свежий базилик и оливковое масло.",
                "موزاريلا فيور دي لاتيه، بيستو الريحان، ستراتشاتيلا الجاموس، سبيك، رقاقة بارميزان، طماطم مسكّرة، ريحان طازج وزيت زيتون.")),
            I("verde-rosso", "Verde Rosso", "23", T(
                "Tomates cerises rôties, jambon de Parme affiné 24 mois, stracciatella di bufala, pesto de basilic maison, huile d'olive et basilic frais.",
                "Roasted cherry tomatoes, 24-month Parma ham, buffalo stracciatella, homemade basil pesto, olive oil and fresh basil.",
                "Pomodorini arrosto, prosciutto di Parma stagionato 24 mesi, stracciatella di bufala, pesto di basilico fatto in casa, olio d'oliva e basilico fresco.",
                "Tomates cherry asados, jamón de Parma curado 24 meses, stracciatella di bufala, pesto casero de albahaca, aceite de oliva y albahaca fresca.",
                "Geröstete Kirschtomaten, 24 Monate gereifter Parmaschinken, Büffel-Stracciatella, hausgemachtes Basilikumpesto, Olivenöl und frisches Basilikum.",
                "Запечённые томаты черри, пармская ветчина 24 месяца, страчателла ди буфала, домашний песто из базилика, оливковое масло и свежий базилик.",
                "طماطم كرزية محمّصة، لحم بارما معتّق 24 شهرًا، ستراتشاتيلا الجاموس، بيستو ريحان منزلي، زيت زيتون وريحان طازج.")),
            I("que-du-love", "Que du love", "24", T(
                "Mozzarella fior di latte, crème de truffe 10 %, burrata crémeuse des Pouilles, jambon de Parme affiné 24 mois et basilic frais.",
                "Fior di latte mozzarella, 10% truffle cream, creamy burrata from Puglia, 24-month Parma ham and fresh basil.",
                "Mozzarella fior di latte, crema al tartufo 10%, burrata cremosa pugliese, prosciutto di Parma stagionato 24 mesi e basilico fresco.",
                "Mozzarella fior di latte, crema de trufa al 10 %, burrata cremosa de Apulia, jamón de Parma curado 24 meses y albahaca fresca.",
                "Fior-di-Latte-Mozzarella, 10 % Trüffelcreme, cremige Burrata aus Apulien, 24 Monate gereifter Parmaschinken und frisches Basilikum.",
                "Моцарелла фьор ди латте, трюфельный крем 10 %, нежная буррата из Апулии, пармская ветчина 24 месяца и свежий базилик.",
                "موزاريلا فيور دي لاتيه، كريمة الكمأة 10%، بوراتا كريمية من بوليا، لحم بارما معتّق 24 شهرًا وريحان طازج."), "que-du-love"),
        ],
    },
    {
        "id": "extra", "group": "cucina", "layout": "list", "open": False,
        "title": "Extra",
        "kicker": T("Pour compléter votre pizza", "To top your pizza", "Per arricchire la pizza", "Para completar tu pizza",
                    "Für Ihre Pizza", "Добавки к пицце", "إضافات للبيتزا"),
        "items": [
            I("x-truffe", "Truffe fraîche", "8"), I("x-burrata", "Burrata", "6"), I("x-bresaola", "Bresaola", "6"),
            I("x-stracciatella", "Stracciatella di bufala", "5"), I("x-cremetruffe", "Crème de truffe 10 %", "5"),
            I("x-parme", "Jambon de Parme", "5"), I("x-thon", "Filet de thon", "5"),
            I("x-bufala", "Mozzarella di bufala", "4"), I("x-fior", "Fior di latte", "4"), I("x-spianata", "Spianata", "4"),
            I("x-speck", "Speck", "4"), I("x-salami", "Salami napolitain", "4"), I("x-mortadelle", "Mortadelle", "4"),
            I("x-artichaut", "Artichaut", "4"), I("x-ricotta", "Ricotta", "4"), I("x-cuit", "Jambon cuit", "4"),
            I("x-gorgonzola", "Gorgonzola", "4"), I("x-champignons", "Champignons", "2"), I("x-cerises", "Tomates cerises", "2"),
            I("x-roquette", "Roquette", "2"), I("x-olives", "Olives", "2"), I("x-anchois", "Anchois", "2"),
            I("x-oignons", "Oignons rouges", "2"), I("x-capres", "Câpres", "2"), I("x-oeuf", "Œuf", "2"),
            I("piccola", "Insalata Piccola", "5", T(
                "Sucrine, roquette, vinaigrette maison.", "Little gem, rocket, homemade vinaigrette.",
                "Lattughino, rucola, vinaigrette della casa.", "Cogollos, rúcula, vinagreta casera.",
                "Romanaherzen, Rucola, hausgemachte Vinaigrette.", "Латук, руккола, домашняя заправка.",
                "خس صغير، جرجير، صلصة منزلية."), None, ["vegan"]),
        ],
    },
    {
        "id": "dolci", "group": "cucina", "layout": "grid", "open": False,
        "title": "Dolci",
        "kicker": T("Pour finir en douceur", "A sweet ending", "Per finire in dolcezza", "Para terminar con dulzura",
                    "Zum süßen Abschluss", "Сладкий финал", "ختام حلو"),
        "items": [
            I("tiramisu", "Tiramisù Agata", "10", T(
                "Crème de mascarpone, biscuit savoiardi, espresso, cacao.", "Mascarpone cream, savoiardi biscuit, espresso, cocoa.",
                "Crema al mascarpone, savoiardi, espresso, cacao.", "Crema de mascarpone, bizcocho savoiardi, espresso, cacao.",
                "Mascarponecreme, Savoiardi, Espresso, Kakao.", "Крем из маскарпоне, печенье савоярди, эспрессо, какао.",
                "كريمة الماسكاربوني، بسكويت سافوياردي، إسبريسو، كاكاو."), "tiramisu", ["veggie"]),
            I("panna-cotta", "Panna Cotta Estate", "10", T(
                "Parfumée à la vanille, marmelade de pomme et pommes séchées.", "Vanilla-flavoured, apple marmalade and dried apples.",
                "Profumata alla vaniglia, marmellata di mele e mele essiccate.", "Aromatizada con vainilla, mermelada de manzana y manzana deshidratada.",
                "Mit Vanille, Apfelmarmelade und getrockneten Äpfeln.", "С ароматом ванили, яблочным мармеладом и сушёными яблоками.",
                "بنكهة الفانيليا، مع مربى التفاح وتفاح مجفف."), None, ["veggie"]),
            I("paris-bronte", "Paris–Bronte", "12", T(
                "Chou garni d'une ganache à la crème de pistache, parsemé de granella de pistaches croquantes.",
                "Choux pastry filled with pistachio cream ganache, sprinkled with crunchy pistachio granella.",
                "Bignè farcito con ganache alla crema di pistacchio, cosparso di granella di pistacchi croccante.",
                "Choux relleno de ganache de crema de pistacho, con pistachos crujientes troceados.",
                "Brandteiggebäck mit Pistaziencreme-Ganache, bestreut mit knusprigen Pistazienstückchen.",
                "Заварное пирожное с ганашем из фисташкового крема, посыпанное хрустящей фисташковой крошкой.",
                "عجينة الشو محشوة بغاناش كريمة الفستق ومرشوشة بالفستق المجروش المقرمش."), "paris-bronte", ["veggie"]),
            I("profiterole", "Profiterole", "12", T(
                "Choux garnis de glace à la vanille, nappés de sauce au chocolat chaud Valrhona 66 % et granella de noisette, chantilly maison.",
                "Choux filled with vanilla ice cream, topped with warm Valrhona 66% chocolate sauce and hazelnut granella, homemade whipped cream.",
                "Bignè ripieni di gelato alla vaniglia, nappati con salsa calda al cioccolato Valrhona 66% e granella di nocciole, panna montata fatta in casa.",
                "Choux rellenos de helado de vainilla, con salsa caliente de chocolate Valrhona 66 % y avellana troceada, nata montada casera.",
                "Windbeutel mit Vanilleeis, warmer Valrhona-Schokoladensauce 66 % und Haselnussstückchen, hausgemachte Schlagsahne.",
                "Профитроли с ванильным мороженым, тёплым соусом из шоколада Valrhona 66 % и ореховой крошкой, домашние взбитые сливки.",
                "شو محشو بآيس كريم الفانيليا، مغطى بصلصة شوكولاتة فالرونا 66% الساخنة وبندق مجروش، مع كريمة مخفوقة منزلية."), None, ["veggie"]),
            I("affogato", "Affogato al Caffè", "7", T(
                "Boule de glace vanille, pistache ou noisette, nappée de notre espresso Lomi.",
                "Scoop of vanilla, pistachio or hazelnut ice cream, topped with our Lomi espresso.",
                "Pallina di gelato alla vaniglia, pistacchio o nocciola, affogata nel nostro espresso Lomi.",
                "Bola de helado de vainilla, pistacho o avellana, bañada con nuestro espresso Lomi.",
                "Eine Kugel Vanille-, Pistazien- oder Haselnusseis, übergossen mit unserem Lomi-Espresso.",
                "Шарик ванильного, фисташкового или орехового мороженого, залитый нашим эспрессо Lomi.",
                "كرة آيس كريم بالفانيليا أو الفستق أو البندق، مغمورة بإسبريسو لومي."), None, ["veggie"]),
            I("gelati", "Glaces artisanales Pedone", "3.5 · 6.5 · 9.5", T(
                "1, 2 ou 3 boules. Demandez nos saveurs du moment !", "1, 2 or 3 scoops. Ask us about our current flavours!",
                "1, 2 o 3 palline. Chiedeteci i gusti del momento!", "1, 2 o 3 bolas. ¡Pregúntanos por los sabores del momento!",
                "1, 2 oder 3 Kugeln. Fragen Sie nach unseren aktuellen Sorten!", "1, 2 или 3 шарика. Спросите о вкусах дня!",
                "كرة أو كرتان أو ثلاث. اسألونا عن نكهات الموسم!"), None, ["veggie"]),
        ],
    },
]
