# -*- coding: utf-8 -*-
from data_food import T, I

# Noms des extras traduits (fr, en, it, es, de, ru, ar)
EXTRA_NAMES = {
    "x-truffe": T("Truffe fraîche", "Fresh truffle", "Tartufo fresco", "Trufa fresca", "Frischer Trüffel", "Свежий трюфель", "كمأة طازجة"),
    "x-burrata": T("Burrata", "Burrata", "Burrata", "Burrata", "Burrata", "Буррата", "بوراتا"),
    "x-bresaola": T("Bresaola", "Bresaola", "Bresaola", "Bresaola", "Bresaola", "Брезаола", "بريزاولا"),
    "x-stracciatella": T("Stracciatella di bufala", "Buffalo stracciatella", "Stracciatella di bufala", "Stracciatella di bufala", "Büffel-Stracciatella", "Страчателла ди буфала", "ستراتشاتيلا الجاموس"),
    "x-cremetruffe": T("Crème de truffe 10 %", "Truffle cream 10%", "Crema al tartufo 10%", "Crema de trufa 10 %", "Trüffelcreme 10 %", "Трюфельный крем 10 %", "كريمة الكمأة 10%"),
    "x-parme": T("Jambon de Parme", "Parma ham", "Prosciutto di Parma", "Jamón de Parma", "Parmaschinken", "Пармская ветчина", "لحم بارما"),
    "x-thon": T("Filet de thon", "Tuna fillet", "Filetto di tonno", "Filete de atún", "Thunfischfilet", "Филе тунца", "فيليه التونة"),
    "x-bufala": T("Mozzarella di bufala", "Buffalo mozzarella", "Mozzarella di bufala", "Mozzarella di bufala", "Büffelmozzarella", "Моцарелла ди буфала", "موزاريلا الجاموس"),
    "x-fior": T("Fior di latte", "Fior di latte", "Fior di latte", "Fior di latte", "Fior di Latte", "Фьор ди латте", "فيور دي لاتيه"),
    "x-spianata": T("Spianata", "Spianata", "Spianata", "Spianata", "Spianata", "Спьяната", "سبياناتا"),
    "x-speck": T("Speck", "Speck", "Speck", "Speck", "Speck", "Спек", "سبيك"),
    "x-salami": T("Salami napolitain", "Neapolitan salami", "Salame napoletano", "Salami napolitano", "Neapolitanische Salami", "Неаполитанская салями", "سلامي نابولي"),
    "x-mortadelle": T("Mortadelle", "Mortadella", "Mortadella", "Mortadela", "Mortadella", "Мортаделла", "مورتاديلا"),
    "x-artichaut": T("Artichaut", "Artichoke", "Carciofo", "Alcachofa", "Artischocke", "Артишок", "خرشوف"),
    "x-ricotta": T("Ricotta", "Ricotta", "Ricotta", "Ricotta", "Ricotta", "Рикотта", "ريكوتا"),
    "x-cuit": T("Jambon cuit", "Cooked ham", "Prosciutto cotto", "Jamón cocido", "Kochschinken", "Варёная ветчина", "لحم مطبوخ"),
    "x-gorgonzola": T("Gorgonzola", "Gorgonzola", "Gorgonzola", "Gorgonzola", "Gorgonzola", "Горгонзола", "غورغونزولا"),
    "x-champignons": T("Champignons", "Mushrooms", "Funghi", "Champiñones", "Champignons", "Шампиньоны", "فطر"),
    "x-cerises": T("Tomates cerises", "Cherry tomatoes", "Pomodorini", "Tomates cherry", "Kirschtomaten", "Томаты черри", "طماطم كرزية"),
    "x-roquette": T("Roquette", "Rocket", "Rucola", "Rúcula", "Rucola", "Руккола", "جرجير"),
    "x-olives": T("Olives", "Olives", "Olive", "Aceitunas", "Oliven", "Оливки", "زيتون"),
    "x-anchois": T("Anchois", "Anchovies", "Acciughe", "Anchoas", "Sardellen", "Анчоусы", "أنشوجة"),
    "x-oignons": T("Oignons rouges", "Red onions", "Cipolle rosse", "Cebolla morada", "Rote Zwiebeln", "Красный лук", "بصل أحمر"),
    "x-capres": T("Câpres", "Capers", "Capperi", "Alcaparras", "Kapern", "Каперсы", "كبر"),
    "x-oeuf": T("Œuf", "Egg", "Uovo", "Huevo", "Ei", "Яйцо", "بيضة"),
}

S_SPRITZ = T("Spritz · 15 cl", "Spritz · 15 cl", "Spritz · 15 cl", "Spritz · 15 cl", "Spritz · 15 cl", "Спритц · 15 cl", "سبريتز · 15 cl")
S_SIGN = T("Cocktails signature", "Signature cocktails", "Cocktail signature", "Cócteles de autor", "Signature-Cocktails", "Авторские коктейли", "كوكتيلات خاصة")
S_SANS = T("Sans alcool", "Alcohol-free", "Analcolici", "Sin alcohol", "Alkoholfrei", "Безалкогольные", "بدون كحول")
S_CLASS = T("Classiques", "Classics", "Classici", "Clásicos", "Klassiker", "Классика", "كلاسيكيات")


def C(id, name, price, sub, *desc):
    return I(id, name, price, T(*desc) if desc else None, None, None, sub)


BAR = [
    {
        "id": "cocktails", "group": "bar", "layout": "drinks", "open": False,
        "title": "Cocktails & Creazioni",
        "kicker": T("Le bar d'Agata", "Agata's bar", "Il bar di Agata", "El bar de Agata", "Agatas Bar", "Бар Agata", "بار أغاتا"),
        "note": T("Notre équipe sera ravie de réaliser tous les cocktails classiques.",
                  "Our team will be delighted to make any classic cocktail.",
                  "Il nostro team sarà felice di prepararvi tutti i cocktail classici.",
                  "Nuestro equipo preparará encantado cualquier cóctel clásico.",
                  "Unser Team mixt Ihnen gerne jeden klassischen Cocktail.",
                  "Наша команда с радостью приготовит любой классический коктейль.",
                  "يسعد فريقنا تحضير جميع الكوكتيلات الكلاسيكية."),
        "items": [
            C("aperol", "Apérol Spritz", "13", S_SPRITZ,
              "Apérol, eau gazeuse, spumante, tranche d'orange.", "Apérol, sparkling water, spumante, orange slice.",
              "Apérol, acqua frizzante, spumante, fetta d'arancia.", "Apérol, agua con gas, spumante, rodaja de naranja.",
              "Apérol, Sprudelwasser, Spumante, Orangenscheibe.", "Апероль, газированная вода, спуманте, долька апельсина.",
              "أبيرول، مياه فوارة، سبومانتي، شريحة برتقال."),
            C("italicus", "Italicus Spritz", "14", S_SPRITZ,
              "Italicus, eau gazeuse, spumante, tranche de citron vert déshydratée.", "Italicus, sparkling water, spumante, dried lime slice.",
              "Italicus, acqua frizzante, spumante, fetta di lime essiccata.", "Italicus, agua con gas, spumante, rodaja de lima deshidratada.",
              "Italicus, Sprudelwasser, Spumante, getrocknete Limettenscheibe.", "Italicus, газированная вода, спуманте, сушёная долька лайма.",
              "إيتاليكوس، مياه فوارة، سبومانتي، شريحة ليمون أخضر مجففة."),
            C("rosato-spritz", "Rosato Spritz", "14", S_SPRITZ,
              "Vermouth Rubino, liqueur de cerise, sirop de rose, eau gazeuse, spumante, tranche d'orange déshydratée.",
              "Vermouth Rubino, cherry liqueur, rose syrup, sparkling water, spumante, dried orange slice.",
              "Vermouth Rubino, liquore di ciliegia, sciroppo di rosa, acqua frizzante, spumante, fetta d'arancia essiccata.",
              "Vermut Rubino, licor de cereza, sirope de rosa, agua con gas, spumante, rodaja de naranja deshidratada.",
              "Wermut Rubino, Kirschlikör, Rosensirup, Sprudelwasser, Spumante, getrocknete Orangenscheibe.",
              "Вермут Rubino, вишнёвый ликёр, розовый сироп, газированная вода, спуманте, сушёная долька апельсина.",
              "فيرموت روبينو، ليكيور الكرز، شراب الورد، مياه فوارة، سبومانتي، شريحة برتقال مجففة."),
            C("agata168", "Agata 168", "15", S_SIGN,
              "Rhum blanc, purée de pêche blanche, sirop elderflower, Cointreau, soda water.", "White rum, white peach purée, elderflower syrup, Cointreau, soda water.",
              "Rum bianco, purea di pesca bianca, sciroppo di sambuco, Cointreau, soda.", "Ron blanco, puré de melocotón blanco, sirope de flor de saúco, Cointreau, soda.",
              "Weißer Rum, weißes Pfirsichpüree, Holunderblütensirup, Cointreau, Soda.", "Белый ром, пюре из белого персика, сироп бузины, Cointreau, содовая.",
              "روم أبيض، هريس الخوخ الأبيض، شراب زهر البيلسان، كوانترو، صودا."),
            C("paloma", "Paloma by Agata", "15", S_SIGN,
              "Tequila infusée au thym, jus de citron vert, soda pamplemousse.", "Thyme-infused tequila, lime juice, grapefruit soda.",
              "Tequila infusa al timo, succo di lime, soda al pompelmo.", "Tequila infusionado con tomillo, zumo de lima, refresco de pomelo.",
              "Mit Thymian infundierter Tequila, Limettensaft, Grapefruit-Soda.", "Текила, настоянная на тимьяне, сок лайма, грейпфрутовая содовая.",
              "تيكيلا منقوعة بالزعتر، عصير ليمون أخضر، صودا الجريب فروت."),
            C("entre-nous", "Entre Nous", "15", S_SIGN,
              "Malfy citron, Campari, jus de citron, sucre de canne, prosecco.", "Malfy lemon gin, Campari, lemon juice, cane sugar, prosecco.",
              "Malfy al limone, Campari, succo di limone, zucchero di canna, prosecco.", "Malfy limón, Campari, zumo de limón, azúcar de caña, prosecco.",
              "Malfy Zitrone, Campari, Zitronensaft, Rohrzucker, Prosecco.", "Malfy лимон, Campari, лимонный сок, тростниковый сахар, просекко.",
              "مالفي بالليمون، كامباري، عصير ليمون، سكر القصب، بروسيكو."),
            C("mezca-luna", "Mezca-Luna", "15", S_SIGN,
              "RosaLuna, Apérol, jus de citron, sucre de canne, pamplemousse.", "RosaLuna, Apérol, lemon juice, cane sugar, grapefruit.",
              "RosaLuna, Apérol, succo di limone, zucchero di canna, pompelmo.", "RosaLuna, Apérol, zumo de limón, azúcar de caña, pomelo.",
              "RosaLuna, Apérol, Zitronensaft, Rohrzucker, Grapefruit.", "RosaLuna, Апероль, лимонный сок, тростниковый сахар, грейпфрут.",
              "روزالونا، أبيرول، عصير ليمون، سكر القصب، جريب فروت."),
            C("basilic-mule", "Basilic Mule", "15", S_SIGN,
              "Gin, feuilles de basilic, sirop de basilic, jus de citron vert, ginger beer.", "Gin, basil leaves, basil syrup, lime juice, ginger beer.",
              "Gin, foglie di basilico, sciroppo di basilico, succo di lime, ginger beer.", "Ginebra, hojas de albahaca, sirope de albahaca, zumo de lima, ginger beer.",
              "Gin, Basilikumblätter, Basilikumsirup, Limettensaft, Ginger Beer.", "Джин, листья базилика, сироп базилика, сок лайма, имбирное пиво.",
              "جن، أوراق ريحان، شراب الريحان، عصير ليمون أخضر، جنجر بير."),
            C("etna-margarita", "Etna Margarita", "15", S_SIGN,
              "Tequila infusée au thym, jus de citron vert, purée de bergamote, sirop de mandarine.", "Thyme-infused tequila, lime juice, bergamot purée, mandarin syrup.",
              "Tequila infusa al timo, succo di lime, purea di bergamotto, sciroppo di mandarino.", "Tequila infusionado con tomillo, zumo de lima, puré de bergamota, sirope de mandarina.",
              "Mit Thymian infundierter Tequila, Limettensaft, Bergamottenpüree, Mandarinensirup.", "Текила на тимьяне, сок лайма, пюре бергамота, мандариновый сироп.",
              "تيكيلا منقوعة بالزعتر، عصير ليمون أخضر، هريس البرغموت، شراب اليوسفي."),
            C("malfy-politan", "Malfy Politan", "15", S_SIGN,
              "Gin Malfy con limone, Cointreau, jus de cranberry, jus de citron.", "Malfy con limone gin, Cointreau, cranberry juice, lemon juice.",
              "Gin Malfy con limone, Cointreau, succo di mirtillo rosso, succo di limone.", "Ginebra Malfy con limone, Cointreau, zumo de arándano rojo, zumo de limón.",
              "Malfy con Limone Gin, Cointreau, Cranberrysaft, Zitronensaft.", "Джин Malfy con limone, Cointreau, клюквенный сок, лимонный сок.",
              "جن مالفي بالليمون، كوانترو، عصير التوت البري، عصير ليمون."),
            C("frangelico-sour", "Frangelico Sour", "15", S_SIGN,
              "Frangelico, jus de citron, amaretto, angostura, le tout en sour.", "Frangelico, lemon juice, amaretto, angostura, shaken as a sour.",
              "Frangelico, succo di limone, amaretto, angostura, in versione sour.", "Frangelico, zumo de limón, amaretto, angostura, al estilo sour.",
              "Frangelico, Zitronensaft, Amaretto, Angostura, als Sour.", "Frangelico, лимонный сок, амаретто, ангостура — в стиле сауэр.",
              "فرانجيليكو، عصير ليمون، أماريتو، أنغوستورا، على طريقة السَّاوَر."),
            C("soiree", "Une soirée inattendue", "15", S_SIGN,
              "Rhum blanc, liqueur de cerise, jus de goyave, soda pamplemousse, jus de citron vert, sirop de noisette.",
              "White rum, cherry liqueur, guava juice, grapefruit soda, lime juice, hazelnut syrup.",
              "Rum bianco, liquore di ciliegia, succo di guava, soda al pompelmo, succo di lime, sciroppo di nocciola.",
              "Ron blanco, licor de cereza, zumo de guayaba, refresco de pomelo, zumo de lima, sirope de avellana.",
              "Weißer Rum, Kirschlikör, Guavensaft, Grapefruit-Soda, Limettensaft, Haselnusssirup.",
              "Белый ром, вишнёвый ликёр, сок гуавы, грейпфрутовая содовая, сок лайма, ореховый сироп.",
              "روم أبيض، ليكيور الكرز، عصير الجوافة، صودا الجريب فروت، عصير ليمون أخضر، شراب البندق."),
            C("summer", "Summer Sunshine", "12", S_SANS,
              "Cranberry, sirop de basilic, jus de citron, jus de pamplemousse.", "Cranberry, basil syrup, lemon juice, grapefruit juice.",
              "Mirtillo rosso, sciroppo di basilico, succo di limone, succo di pompelmo.", "Arándano rojo, sirope de albahaca, zumo de limón, zumo de pomelo.",
              "Cranberry, Basilikumsirup, Zitronensaft, Grapefruitsaft.", "Клюква, сироп базилика, лимонный сок, грейпфрутовый сок.",
              "توت بري، شراب الريحان، عصير ليمون، عصير جريب فروت."),
            C("passionne", "Le Passionné", "12", S_SANS,
              "Purée de passion, jus de citron, sirop de mandarine, limonade.", "Passion fruit purée, lemon juice, mandarin syrup, lemonade.",
              "Purea di frutto della passione, succo di limone, sciroppo di mandarino, limonata.", "Puré de maracuyá, zumo de limón, sirope de mandarina, limonada.",
              "Maracujapüree, Zitronensaft, Mandarinensirup, Limonade.", "Пюре маракуйи, лимонный сок, мандариновый сироп, лимонад.",
              "هريس فاكهة الشغف، عصير ليمون، شراب اليوسفي، ليموناضة."),
            C("negroni", "Negroni Agata", "15", S_CLASS,
              "Del Professore rosso, Campari, gin.", "Del Professore rosso, Campari, gin.", "Del Professore rosso, Campari, gin.",
              "Del Professore rosso, Campari, ginebra.", "Del Professore rosso, Campari, Gin.", "Del Professore rosso, Campari, джин.",
              "ديل بروفيسوري روسو، كامباري، جن."),
            C("king-negroni", "King Negroni", "17", S_CLASS,
              "Barolo Chinato, Maraschino, gin, Campari.", "Barolo Chinato, Maraschino, gin, Campari.", "Barolo Chinato, Maraschino, gin, Campari.",
              "Barolo Chinato, Maraschino, ginebra, Campari.", "Barolo Chinato, Maraschino, Gin, Campari.", "Бароло Кинато, мараскино, джин, Campari.",
              "بارولو كيناتو، ماراسكينو، جن، كامباري."),
            C("bellini", "Bellini", "15", S_CLASS,
              "Crème de pêche, purée de pêche blanche, prosecco.", "Peach liqueur, white peach purée, prosecco.",
              "Crema di pesca, purea di pesca bianca, prosecco.", "Crema de melocotón, puré de melocotón blanco, prosecco.",
              "Pfirsichlikör, weißes Pfirsichpüree, Prosecco.", "Персиковый ликёр, пюре из белого персика, просекко.",
              "ليكيور الخوخ، هريس الخوخ الأبيض، بروسيكو."),
            C("cosmopolitan", "Cosmopolitan", "15", S_CLASS,
              "Vodka, Cointreau, jus de cranberry, jus de citron.", "Vodka, Cointreau, cranberry juice, lemon juice.",
              "Vodka, Cointreau, succo di mirtillo rosso, succo di limone.", "Vodka, Cointreau, zumo de arándano rojo, zumo de limón.",
              "Wodka, Cointreau, Cranberrysaft, Zitronensaft.", "Водка, Cointreau, клюквенный сок, лимонный сок.",
              "فودكا، كوانترو، عصير التوت البري، عصير ليمون."),
            C("espresso-martini", "Espresso Martini", "15", S_CLASS,
              "Vodka infusée à la fève de tonka, Fair Café, espresso Lomi, sirop de sucre.", "Tonka-bean-infused vodka, Fair Café, Lomi espresso, sugar syrup.",
              "Vodka infusa alla fava tonka, Fair Café, espresso Lomi, sciroppo di zucchero.", "Vodka infusionado con haba tonka, Fair Café, espresso Lomi, sirope de azúcar.",
              "Mit Tonkabohne infundierter Wodka, Fair Café, Lomi-Espresso, Zuckersirup.", "Водка на бобах тонка, Fair Café, эспрессо Lomi, сахарный сироп.",
              "فودكا منقوعة بحبوب التونكا، فير كافيه، إسبريسو لومي، شراب السكر."),
            C("pornstar", "Porn Star Martini", "15", S_CLASS,
              "Vodka infusée à la vanille, fruit de la passion, sirop de vanille, jus de citron, shot de prosecco.",
              "Vanilla-infused vodka, passion fruit, vanilla syrup, lemon juice, a shot of prosecco.",
              "Vodka infusa alla vaniglia, frutto della passione, sciroppo di vaniglia, succo di limone, shot di prosecco.",
              "Vodka infusionado con vainilla, maracuyá, sirope de vainilla, zumo de limón, chupito de prosecco.",
              "Vanille-Wodka, Maracuja, Vanillesirup, Zitronensaft, ein Shot Prosecco.",
              "Водка на ванили, маракуйя, ванильный сироп, лимонный сок, шот просекко.",
              "فودكا منقوعة بالفانيليا، فاكهة الشغف، شراب الفانيليا، عصير ليمون، رشفة بروسيكو."),
        ],
    },
]

# --- Vins & boissons : listes (noms propres, pas de traduction des étiquettes)
def W(id, name, price, sub, tags=None):
    return I(id, name, price, None, None, tags, sub)


V_SP = T("Spumante", "Spumante", "Spumante", "Spumante", "Spumante", "Спуманте", "سبومانتي")
V_BI = T("Bianco", "White", "Bianco", "Blanco", "Weiß", "Белое", "أبيض")
V_RO = T("Rosso", "Red", "Rosso", "Tinto", "Rot", "Красное", "أحمر")
V_RS = T("Rosato", "Rosé", "Rosato", "Rosado", "Rosé", "Розовое", "وردي")
V_DS = T("Vin de dessert", "Dessert wine", "Vino da dessert", "Vino de postre", "Dessertwein", "Десертное вино", "نبيذ الحلوى")
BIO = ["bio"]

BAR += [
    {
        "id": "calice", "group": "bar", "layout": "drinks", "open": False,
        "title": "Vini al Calice",
        "kicker": T("Au verre · 14 cl", "By the glass · 14 cl", "Al bicchiere · 14 cl", "Por copa · 14 cl", "Im Glas · 14 cl", "По бокалам · 14 cl", "بالكأس · 14 cl"),
        "items": [
            W("g1", "Col di Luna — Prosecco Treviso Extra Dry DOC 2023", "9.5", V_SP),
            W("g2", "Il Coltri — Chardonnay IGT Toscane 2024", "8.5", V_BI),
            W("g3", "Casa D'Ambra — Ischia Bianco DOC 2024", "9.5", V_BI),
            W("g4", "Tenuta Giustini — Patù Primitivo Salento IGT 2024", "9", V_RO),
            W("g5", "Caleselle — Valpolicella Classico DOC 2023", "10", V_RO),
            W("g6", "Noelia Ricci — Il Sangiovese di Romagna DOC 2024", "12", V_RO),
            W("g7", "Pian delle Querci — Brunello di Montalcino DOCG 2019", "15", V_RO),
            W("g8", "Santi — Infinito Chiaretto di Bardolino DOC 2024", "9", V_RS),
            W("g9", "Barolo Chinato · 8 cl", "16", V_DS),
        ],
    },
    {
        "id": "champagne", "group": "bar", "layout": "drinks", "open": False,
        "title": "Champagne",
        "kicker": T("La bouteille", "By the bottle", "La bottiglia", "La botella", "Die Flasche", "Бутылка", "الزجاجة"),
        "items": [
            W("c1", "Charles Heidsieck — Brut", "95", None),
            W("c2", "Bollinger — Brut Spéciale Cuvée", "180", None),
            W("c3", "Perrier-Jouët — Belle Époque Millésimé", "290", None),
        ],
    },
    {
        "id": "vini-italiani", "group": "bar", "layout": "drinks", "open": False,
        "title": "Vini Italiani",
        "kicker": T("La bouteille · 75 cl", "By the bottle · 75 cl", "La bottiglia · 75 cl", "La botella · 75 cl", "Die Flasche · 75 cl", "Бутылка · 75 cl", "الزجاجة · 75 cl"),
        "note": T("Certains millésimes peuvent changer en cours d'année.", "Some vintages may change during the year.",
                  "Alcune annate possono cambiare nel corso dell'anno.", "Algunas añadas pueden cambiar a lo largo del año.",
                  "Einige Jahrgänge können sich im Laufe des Jahres ändern.", "Некоторые урожаи могут меняться в течение года.",
                  "قد تتغير بعض سنوات الإنتاج خلال العام."),
        "items": [
            W("i1", "Col di Luna — Prosecco Treviso Extra Dry DOC 2024 · Vénétie", "39", V_SP),
            W("i2", "Cantina della Volta — Lambrusco di Modena DOC 2023 · Émilie-Romagne", "40", V_SP),
            W("i3", "Poderi Marcarini — Moscato d'Asti DOCG · Piémont", "42", V_SP),
            W("i4", "Santi — Infinito Chiaretto di Bardolino DOC 2024 · Vénétie", "39", V_RS),
            W("i5", "Marco Sara — Ribolla Gialla DOC 2024 · Frioul", "42", V_BI, BIO),
            W("i6", "Alta Mora — Etna Bianco de Cusumano DOC 2022/2023 · Sicile", "68", V_BI),
            W("i7", "Giuseppe Cortese — Chardonnay Langhe Scapulin DOC 2023/2024 · Piémont", "56", V_BI),
            W("i8", "La Marca di San Michele — Passolento, Verdicchio Riserva DOCG 2017 · Marches", "66", V_BI, BIO),
            W("i9", "Il Coltri — Chardonnay IGT Toscane 2024 · Toscane", "35", V_BI),
            W("i10", "Monteraponi — Trebbiano IGT 2021 · Toscane", "180", V_BI),
            W("i11", "Casa D'Ambra — Ischia Bianco DOC 2024 · Campanie", "45", V_BI),
            W("i12", "Cantina Pepi — Nero d'Avola IGT 2024 · Sicile", "36", V_RO),
            W("i13", "Tenuta Giustini — Patù Primitivo Salento IGT 2024/2025 · Pouilles", "39", V_RO),
            W("i14", "La Valentina — Montepulciano d'Abruzzo DOC 2023 · Abruzzes", "40", V_RO),
            W("i15", "Caleselle — Valpolicella Classico DOC 2023 · Vénétie", "48", V_RO),
            W("i16", "Santi — Santico, Amarone della Valpolicella DOCG 2023 · Vénétie", "149", V_RO),
            W("i17", "Noelia Ricci — Il Sangiovese di Romagna DOC 2024 · Émilie-Romagne", "56", V_RO),
            W("i18", "Orgosa — Nero di Orgosa IGT 2021 · Sardaigne", "58", V_RO, ["nature"]),
            W("i19", "Argiolas — Korem IGT 2020 · Sardaigne", "110", V_RO),
            W("i20", "Marco Sara — Schioppettino DOC 2022 · Frioul", "65", V_RO, BIO),
            W("i21", "Francesco Versio — Dolcetto Dogliani DOCG 2023 · Piémont", "46", V_RO),
            W("i22", "Sette — Barbera d'Asti DOCG 2023 · Piémont", "54", V_RO, ["biodyn"]),
            W("i23", "Marco Parusso — Langhe Nebbiolo « Ël Sartù » DOC 2023 · Piémont", "59", V_RO),
            W("i24", "Giuseppe Cortese — Barbaresco DOCG 2021 · Piémont", "110", V_RO),
            W("i25", "Boroli — Barolo del Comune di Castiglione Falletto DOCG 2020 · Piémont", "169", V_RO),
            W("i26", "Roberto Voerzio — Barolo del Comune di La Morra DOCG 2020 · Piémont", "255", V_RO),
            W("i27", "Istine — Chianti Classico DOCG 2022 · Toscane", "62", V_RO),
            W("i28", "Monteraponi — Chianti Classico DOCG 2023 · Toscane", "76", V_RO, BIO),
            W("i29", "Fattoi — Rosso di Montalcino DOC 2023 · Toscane", "64", V_RO),
            W("i30", "Pian delle Querci — Brunello di Montalcino DOCG 2017/2018 · Toscane", "82", V_RO),
            W("i31", "Tenuta San Guido — Guidalberto IGT 2022 · Toscane", "85", V_RO),
            W("i32", "Tenuta San Guido — Guidalberto IGT 2022 · Magnum 150 cl", "160", V_RO),
            W("i33", "Boscarelli — Vino Nobile di Montepulciano « Il Nocio » DOCG 2016 · Toscane", "170", V_RO),
            W("i34", "Biondi Santi — Brunello di Montalcino DOCG 2018 · Toscane", "345", V_RO),
            W("i35", "Antinori — Solaia IGT 2017 · Toscane", "530", V_RO),
            W("i36", "Tenuta San Guido — Sassicaia, Bolgheri DOC 2020 · Toscane", "640", V_RO),
            W("i37", "Case Basse Soldera — Toscana IGT 2020 · Toscane", "860", V_RO),
        ],
    },
    {
        "id": "vins-france", "group": "bar", "layout": "drinks", "open": False,
        "title": "Vins de France",
        "kicker": T("La bouteille · 75 cl", "By the bottle · 75 cl", "La bottiglia · 75 cl", "La botella · 75 cl", "Die Flasche · 75 cl", "Бутылка · 75 cl", "الزجاجة · 75 cl"),
        "items": [
            W("f1", "Pascal Jolivet — Sancerre 2025 · Loire", "59", V_BI),
            W("f2", "Domaine Billaud-Simon — Chablis 2023 · Bourgogne", "60", V_BI),
            W("f3", "Vincent Girardin — Meursault « Vieilles Vignes » 2022 · Bourgogne", "160", V_BI),
            W("f4", "Domaine Faiveley — Mercurey « Vieilles Vignes » 2023 · Bourgogne", "66", V_RO),
            W("f5", "Vincent Girardin — Beaune 1er Cru « Les Aigrots » 2018 · Bourgogne", "129", V_RO),
            W("f6", "Tardieu-Laurent — Crozes-Hermitage « Vieilles Vignes » 2021/2022 · Rhône", "70", V_RO),
            W("f7", "Moulin de La Lagune — Haut-Médoc 2017/2020 · Bordeaux", "65", V_RO),
            W("f8", "Château Langoa Barton — Saint-Julien 3e Grand Cru Classé 2015 · Bordeaux", "145", V_RO),
            W("f9", "Figuière — Côtes de Provence « Première » 2024/2025 · Provence", "49", V_RS),
        ],
    },
    {
        "id": "spiriti", "group": "bar", "layout": "drinks", "open": False,
        "title": "Spiriti",
        "kicker": T("4 cl · supplément soda ou soft 3", "4 cl · soda or soft drink +3", "4 cl · supplemento soda o bibita 3",
                    "4 cl · suplemento refresco 3", "4 cl · Soda oder Softdrink +3", "4 cl · содовая или софт-дринк +3", "4 cl · إضافة صودا أو مشروب غازي 3"),
        "items": [
            W("s1", "Beefeater", "12", "Gin"), W("s2", "Bombay Sapphire", "13", "Gin"), W("s3", "Malfy con Limone", "14", "Gin"), W("s4", "Hendrick's", "15", "Gin"),
            W("s5", "Żubrówka Biała", "12", "Vodka"), W("s6", "Grey Goose", "15", "Vodka"),
            W("s7", "Havana Club 3", "12", "Rhum"), W("s8", "Havana Club 7", "15", "Rhum"), W("s9", "Diplomático", "15", "Rhum"),
            W("s10", "Cihuatán 8 ans", "15", "Rhum"), W("s11", "Zacapa Solera 23", "18", "Rhum"),
            W("s12", "Cachaça Janeiro", "11", "Cachaça"),
            W("s13", "RosaLuna", "14", "Tequila & Mezcal"), W("s14", "Don Julio Blanco", "15", "Tequila & Mezcal"),
            W("s15", "Del Maguey Vida Mezcal", "16", "Tequila & Mezcal"), W("s16", "José Cuervo Especial", "16", "Tequila & Mezcal"),
            W("s17", "Amor Mio", "29", "Tequila & Mezcal"),
            W("s18", "Macchu Pisco", "16", "Pisco"),
            W("s19", "Four Roses", "12", "Bourbon"), W("s20", "Maker's Mark", "15", "Bourbon"),
            W("s21", "Johnnie Walker Black Label", "14", "Scotch Whisky"), W("s22", "Chivas Regal 12", "15", "Scotch Whisky"),
            W("s23", "Talisker Port Ruighe", "14", "Single Malt"), W("s24", "Oban 14", "16", "Single Malt"),
            W("s25", "Lagavulin 16", "19", "Single Malt"), W("s26", "Glenlivet 18", "22", "Single Malt"),
            W("s27", "Jameson", "12", "Irish"), W("s28", "Nikka From the Barrel", "18", "Japon · Japan"),
            W("s29", "Martell VSOP Red Barrels", "16", "Cognac"), W("s30", "Martell XO", "32", "Cognac"),
            W("s31", "Janneau VS", "15", "Armagnac"), W("s32", "Beaujour", "15", "Calvados"),
        ],
    },
    {
        "id": "liquori", "group": "bar", "layout": "drinks", "open": False,
        "title": "Liquori & Digestivi",
        "kicker": T("4 cl", "4 cl", "4 cl", "4 cl", "4 cl", "4 cl", "4 cl"),
        "items": [
            W("l1", "Limoncello", "11", "Liquori"), W("l2", "Amaro Montenegro", "11", "Liquori"), W("l3", "Vecchio Amaro del Capo", "11", "Liquori"),
            W("l4", "Amaretto Disaronno", "11", "Liquori"), W("l5", "Sambuca", "11", "Liquori"), W("l6", "Frangelico", "11", "Liquori"),
            W("l7", "Italicus", "11", "Liquori"), W("l8", "Galliano Autentico", "11", "Liquori"), W("l9", "Maraschino Luxardo", "11", "Liquori"),
            W("l10", "Fair Café", "11", "Liquori"), W("l11", "Get 27", "11", "Liquori"), W("l12", "Cointreau", "11", "Liquori"),
            W("l13", "Bailey's", "11", "Liquori"),
            W("l14", "Sarpa di Poli", "12", "Grappa"), W("l15", "Poli Cleopatra Moscato Oro", "14", "Grappa"),
            W("l16", "Morand — Eau-de-vie Williamine", "10", "Digestivi"), W("l17", "Morand — Eau-de-vie Framboise", "10", "Digestivi"),
        ],
    },
    {
        "id": "birre", "group": "bar", "layout": "drinks", "open": False,
        "title": "Birre & Analcolici",
        "kicker": T("Bières, eaux, jus et sodas", "Beers, waters, juices & sodas", "Birre, acque, succhi e bibite", "Cervezas, aguas, zumos y refrescos",
                    "Biere, Wasser, Säfte & Softdrinks", "Пиво, вода, соки и газировка", "بيرة، مياه، عصائر ومشروبات غازية"),
        "items": [
            W("b1", "Peroni Nastro Azzurro · pression 25 cl", "6.5", T("Bières", "Beers", "Birre", "Cervezas", "Biere", "Пиво", "بيرة")),
            W("b2", "Peroni Nastro Azzurro · pression 50 cl", "11", T("Bières", "Beers", "Birre", "Cervezas", "Biere", "Пиво", "بيرة")),
            W("b3", "Peroni Nastro Azzurro · bouteille 33 cl", "7", T("Bières", "Beers", "Birre", "Cervezas", "Biere", "Пиво", "بيرة")),
            W("b4", "Ichnusa Non Filtrata · 33 cl", "7", T("Bières", "Beers", "Birre", "Cervezas", "Biere", "Пиво", "بيرة")),
            W("a1", "Campari · 4 cl", "9", T("Apéritifs", "Aperitifs", "Aperitivi", "Aperitivos", "Aperitifs", "Аперитивы", "مشروبات فاتحة للشهية")),
            W("a2", "Del Professore Vermouth Rosso · 8 cl", "9", T("Apéritifs", "Aperitifs", "Aperitivi", "Aperitivos", "Aperitifs", "Аперитивы", "مشروبات فاتحة للشهية")),
            W("a3", "Del Professore Vermouth Bianco · 8 cl", "9", T("Apéritifs", "Aperitifs", "Aperitivi", "Aperitivos", "Aperitifs", "Аперитивы", "مشروبات فاتحة للشهية")),
            W("a4", "Ricard · 4 cl", "9", T("Apéritifs", "Aperitifs", "Aperitivi", "Aperitivos", "Aperitifs", "Аперитивы", "مشروبات فاتحة للشهية")),
            W("a5", "Porto Sandeman · 8 cl", "9", T("Apéritifs", "Aperitifs", "Aperitivi", "Aperitivos", "Aperitifs", "Аперитивы", "مشروبات فاتحة للشهية")),
            W("a6", "Kir vin blanc (cassis, mûre, framboise, pêche)", "9", T("Apéritifs", "Aperitifs", "Aperitivi", "Aperitivos", "Aperitifs", "Аперитивы", "مشروبات فاتحة للشهية")),
            W("e1", "Acqua Panna · 75 cl", "7", T("Eaux", "Waters", "Acque", "Aguas", "Wasser", "Вода", "مياه")),
            W("e2", "San Pellegrino · 75 cl", "7", T("Eaux", "Waters", "Acque", "Aguas", "Wasser", "Вода", "مياه")),
            W("e3", "Perrier · 33 cl", "6", T("Eaux", "Waters", "Acque", "Aguas", "Wasser", "Вода", "مياه")),
            W("j1", "Maison Meneau · orange / tomate · 25 cl", "7", T("Jus", "Juices", "Succhi", "Zumos", "Säfte", "Соки", "عصائر"), BIO),
            W("j2", "Maison Meneau · poire / fraise-framboise · 25 cl", "7", T("Jus", "Juices", "Succhi", "Zumos", "Säfte", "Соки", "عصائر"), BIO),
            W("j3", "Jus d'orange pressé", "8", T("Jus", "Juices", "Succhi", "Zumos", "Säfte", "Соки", "عصائر")),
            W("o1", "Polara · Limonata · 27,5 cl", "7", T("Limonata artisanale", "Artisanal lemonade", "Limonata artigianale", "Limonada artesanal", "Handwerkliche Limonade", "Ремесленный лимонад", "ليموناضة حرفية")),
            W("o2", "Polara · Aranciata · 27,5 cl", "7", T("Limonata artisanale", "Artisanal lemonade", "Limonata artigianale", "Limonada artesanal", "Handwerkliche Limonade", "Ремесленный лимонад", "ليموناضة حرفية")),
            W("o3", "Polara · Gazzosa · 27,5 cl", "7", T("Limonata artisanale", "Artisanal lemonade", "Limonata artigianale", "Limonada artesanal", "Handwerkliche Limonade", "Ремесленный лимонад", "ليموناضة حرفية")),
            W("d1", "Coca-Cola · 33 cl", "7", "Sodas"), W("d2", "Coca-Cola Zero · 33 cl", "7", "Sodas"),
            W("d3", "Fuzetea pêche · 25 cl", "6", "Sodas"), W("d4", "Fever-Tree Tonic · 20 cl", "6", "Sodas"),
            W("d5", "Fever-Tree Ginger Beer · 20 cl", "6", "Sodas"), W("d6", "Fever-Tree Ginger Ale · 20 cl", "6", "Sodas"),
            W("d7", "Red Bull", "6", "Sodas"),
        ],
    },
    {
        "id": "caffetteria", "group": "bar", "layout": "drinks", "open": False,
        "title": "La Caffetteria",
        "kicker": T("Café Lomi « J'ai Deux Amours », bio", "Lomi coffee « J'ai Deux Amours », organic", "Caffè Lomi « J'ai Deux Amours », bio",
                    "Café Lomi « J'ai Deux Amours », ecológico", "Lomi-Kaffee « J'ai Deux Amours », bio", "Кофе Lomi « J'ai Deux Amours », органик", "قهوة لومي « J'ai Deux Amours »، عضوية"),
        "items": [
            W("k1", "Espresso", "3.5", None), W("k2", "Décaféiné", "3.5", None), W("k3", "Noisette", "3.7", None),
            W("k4", "Macchiato", "3.8", None), W("k5", "Double espresso", "6", None), W("k6", "Café américain", "6", None),
            W("k7", "Café crème", "6", None), W("k8", "Chocolat chaud", "6", None), W("k9", "Cappuccino", "7", None),
            W("k10", "Thé Dammann Frères · Earl Grey, thé vert menthe, Darjeeling", "7", None),
            W("k11", "Infusion · tilleul, camomille", "7", None),
        ],
    },
]

INFO = {
    "address": "168 Boulevard Saint-Germain · Paris Rive Gauche",
    "wifi": "AGATA GUEST",
    "wifiCode": "168stgermain",
    "quote": "Il meglio deve ancora venire…",
    "lines": T(
        ["Avez-vous des allergies alimentaires ? Dites-le à notre équipe : elle vous apportera la liste des allergènes et vous renseignera sur chaque plat.",
         "Prix nets en euros, service compris. TVA 20 % et 10 %. La maison n'accepte pas les chèques.",
         "Service continu le samedi. Préparé avec amour et des ingrédients frais.",
         "Origine des charcuteries : Italie · Origine des viandes : France.",
         "L'abus d'alcool est dangereux pour la santé, à consommer avec modération."],
        ["Any food allergies? Please tell our team: they will bring you the allergen list and details on each dish.",
         "Net prices in euros, service included. VAT 20% and 10%. Cheques are not accepted.",
         "Continuous service on Saturdays. Prepared with love and fresh ingredients.",
         "Cured meats from Italy · Meat from France.",
         "Alcohol abuse is dangerous for your health. Please drink responsibly."],
        ["Avete allergie alimentari? Ditelo al nostro staff: vi porterà la lista degli allergeni e vi informerà su ogni piatto.",
         "Prezzi netti in euro, servizio incluso. IVA 20% e 10%. Non si accettano assegni.",
         "Servizio continuato il sabato. Preparato con amore e ingredienti freschi.",
         "Salumi di origine italiana · Carni di origine francese.",
         "L'abuso di alcol è dannoso per la salute, bevete con moderazione."],
        ["¿Tiene alergias alimentarias? Díganoslo: nuestro equipo le traerá la lista de alérgenos y le informará sobre cada plato.",
         "Precios netos en euros, servicio incluido. IVA 20 % y 10 %. No se aceptan cheques.",
         "Servicio continuo los sábados. Preparado con amor e ingredientes frescos.",
         "Embutidos de Italia · Carnes de Francia.",
         "El abuso del alcohol es peligroso para la salud, consúmalo con moderación."],
        ["Haben Sie Lebensmittelallergien? Sagen Sie es unserem Team: Es bringt Ihnen die Allergenliste und informiert Sie zu jedem Gericht.",
         "Nettopreise in Euro, Service inbegriffen. MwSt. 20 % und 10 %. Schecks werden nicht angenommen.",
         "Samstags durchgehend geöffnet. Mit Liebe und frischen Zutaten zubereitet.",
         "Wurstwaren aus Italien · Fleisch aus Frankreich.",
         "Übermäßiger Alkoholkonsum schadet der Gesundheit. Bitte genießen Sie verantwortungsvoll."],
        ["Есть пищевая аллергия? Сообщите нашей команде: вам принесут список аллергенов и расскажут о каждом блюде.",
         "Цены в евро, обслуживание включено. НДС 20 % и 10 %. Чеки не принимаются.",
         "По субботам работаем без перерыва. Приготовлено с любовью из свежих продуктов.",
         "Мясные деликатесы из Италии · Мясо из Франции.",
         "Чрезмерное употребление алкоголя вредит вашему здоровью."],
        ["هل لديكم حساسية من أطعمة معينة؟ أخبروا فريقنا وسيحضر لكم قائمة مسببات الحساسية ويشرح لكم كل طبق.",
         "الأسعار صافية باليورو، شاملة الخدمة. ضريبة القيمة المضافة 20% و10%. لا نقبل الشيكات.",
         "خدمة متواصلة يوم السبت. مُحضَّر بحب ومن مكونات طازجة.",
         "اللحوم المقددة من إيطاليا · اللحوم من فرنسا.",
         "الإفراط في تناول الكحول يضر بالصحة، يُرجى الاعتدال."]),
}
